name: scrap_it
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_core_platform_interface: ^4.2.5
  plugin_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  dcdg: ^4.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  google_api_availability: ^3.0.0
  http: ^0.13.0
  image_picker: ^0.7.0
  intl: ^0.17.0
  provider: ^6.0.2
  url_launcher: ^6.0.0
  uuid: ^3.0.6
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  google_fonts:
  flutter_polyline_points: ^1.0.0
  fluttericon: ^2.0.0


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages